server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zyplayer_doc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: 123456
  #配置Mapper.xml映射文件
mybatis:
  mapper-locations: classpath*:mapper/*.xml

